language: python
python:
- '2.7'
cache: pip
install:
- python setup.py install
script:
- python setup.py test
deploy:
  provider: pypi
  user: snips
  password:
    secure: PbV3Qyr7rJQFfe3aBMs6yg1Ox3YErImThrtFAEZj11fqI7/7TJ8HI7va+5Jf2ne3lASNThGWix2p0KjNek8I1aoHw1977dRoqnK8B0SipqXR9U6xOQyGbx2O7Ir68MK4ynm/iNWAc+cCDKLXzSRkSBSUfELvlVXlUzWisXO0HhyR6b4Mc1BOnK6ihU9EnAS7fu5dWzEsFXePVaO28FRq9pDyV8IBfGH6Z4JlVK1DyQdozJDm+kDmgDTjsUyxQIlTINJO7FqNkrCbAvWgKEJnbCVQYn+PfeqEhELcSHLIfEhdL5X5fd9X2gEXGIbICgQvYlrh01BZ3EMhdMNRjAyeTy+Ayhkm4JKpkgy+JbSk9hjzaHrKAsIkYGequu5LMHZoBhguiWCTPVPx3F5XHqmKA8Oa/hWcnxqWh6NLl1sXE61VC+6DzEgSDwceyF/uxoFK86GUVYzd8obrujARAdaLLmdWWblAHrj52D9OEwUbvxGQftYM2itymUIvmjkCLQqFxj4nPmC+5g4vibXHub11piUM0mJKyGkZ72qNMpBDeLw9MwQkv9ZSy98o5i403xNbPr6R3GDtxRZzMfr3vS6sQQhj4hTRTWLJcqHeSP7D1LuJyT5iUA3cjxjHDWbhPzLkIZqTrx8reCyKRwkJC36zPw+W7yyxiJ4IZRHjBa3EsGI=
  on:
    tags: true
    branch: master
